version: '3'

volumes:
  pg_data:
  static_volume:
  media_volume:
  data_volume:
  redis_data:
  sent_emails:

services:
  db:
    image: postgres:13.10
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data/
  redis:
    image: redis/redis-stack-server:latest
    ports:
      - 6379:6379
    volumes:
      - redis_data:/local-data/
  backend:
    build: ./backend/
    env_file: .env
    depends_on:
      - db
      - redis
    volumes:
      - static_volume:/backend_static/
      - media_volume:/media/
      - data_volume:/data/
    ports:
      - 8012:80
  worker:
    build: ./backend/
    command: celery -A psyhelp worker --loglevel info
    env_file: .env
    volumes:
      - sent_emails:/app/sent_emails/
    depends_on:
      - backend
      - redis
  gateway:
    build: ./infra/
    env_file: .env
    volumes:
      - static_volume:/staticfiles/
      - media_volume:/media/
    ports:
      - 8011:80