
version: '3'

volumes:
  pg_data_production:
  static_volume:
  media_volume:
  data_volume:
  redis_data:

services:
  db:
    image: postgres:13.10
    env_file: .env
    restart: always
    volumes:
      - pg_data_production:/var/lib/postgresql/data/
    ports:
      - 5432:5432
  redis-stack:
    image: redis/redis-stack-server:latest
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
      - redis_data:/local-data/
  backend:
    image: sergeyxx/psyhelp_backend
    env_file: .env
    depends_on:
      - db
      - redis-stack
    restart: always
    volumes:
      - static_volume:/backend_static/
      - media_volume:/media/
      - data_volume:/data/
  gateway:
    image: sergeyxx/psyhelp_gateway
    env_file: .env
    restart: always
    volumes:
      - static_volume:/staticfiles/
      - media_volume:/media/
    ports:
      - 8011:80