
version: '3'

volumes:
  pg_data_production:
  static_volume:
  media_volume:
  data_volume:
  redis_data:
  sent_emails:

services:
  db:
    image: postgres:13.10
    env_file: .env
    restart: always
    volumes:
      - pg_data_production:/var/lib/postgresql/data/
    ports:
      - 5432:5432
  redis:
    image: redis/redis-stack-server:latest
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
      - redis_data:/local-data/
  backend:
    image: sergeyxx/psyhelp_backend
    env_file: .env
    depends_on:
      - db
      - redis
    restart: always
    volumes:
      - static_volume:/backend_static/
      - media_volume:/media/
      - data_volume:/data/
  frontend:
    image: sergeyxx/psyhelp_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static/
  worker:
    image: sergeyxx/psyhelp_backend
    command: celery -A psyhelp worker --loglevel info
    env_file: .env
    volumes:
      - sent_emails:/app/sent_emails/
    depends_on:
      - backend
      - redis
  gateway:
    image: sergeyxx/psyhelp_gateway
    env_file: .env
    restart: always
    volumes:
      - static_volume:/staticfiles/
      - media_volume:/media/
    ports:
      - 8011:80