# Generated by Django 3.2.16 on 2024-01-10 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='id')),
                ('is_active', models.BooleanField(default=True)),
                ('consumer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumer_chats', to=settings.AUTH_USER_MODEL)),
                ('psychologist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='psychologist_chats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'чат',
                'verbose_name_plural': 'чаты',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='id')),
                ('date_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата отправки')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
                ('chat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chat')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
                'ordering': ('-date_time',),
            },
        ),
    ]
