# Generated by Django 3.2.16 on 2024-02-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_url_sent',
            field=models.BooleanField(default=False),
        ),
    ]
