# Generated by Django 3.2.16 on 2024-02-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='connected_clients',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
