# Generated by Django 3.2.16 on 2024-01-12 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_psy_author',
        ),
        migrations.AddField(
            model_name='message',
            name='author_id',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
