# Generated by Django 3.2.16 on 2024-01-12 10:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_auto_20240112_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='author_id',
        ),
        migrations.AddField(
            model_name='chat',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='is_psy_author',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chats.chat'),
        ),
    ]
