# Generated by Django 3.2.16 on 2024-01-13 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_auto_20240112_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='is_finished',
            new_name='active',
        ),
    ]
