# Generated by Django 3.2.16 on 2024-01-13 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0006_rename_is_finished_chat_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
