# Generated by Django 3.2.16 on 2024-01-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0007_alter_chat_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='chat_secret_key',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
