# Generated by Django 3.2.16 on 2024-01-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0008_chat_chat_secret_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='connected_clients',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
