# Generated by Django 3.2.16 on 2024-02-09 12:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import users.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^(?!.*\\s{2})(?!.*\\-{2})', 'Двойные дефисы и пробелы запрещены'), django.core.validators.RegexValidator('^[а-яА-ЯёЁ]+(?:[- ]?[а-яА-ЯёЁ]+)*$', 'Разрешены только буквы русского алфавита, дефис, и символ пробела. Дефисы и пробелы не могут находиться в начале и в конце ввода')], verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^(?!.*\\s{2})(?!.*\\-{2})', 'Двойные дефисы и пробелы запрещены'), django.core.validators.RegexValidator('^[а-яА-ЯёЁ]+(?:[- ]?[а-яА-ЯёЁ]+)*$', 'Разрешены только буквы русского алфавита, дефис, и символ пробела. Дефисы и пробелы не могут находиться в начале и в конце ввода')], verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator('^(?!.*\\s{2})(?!.*\\-{2})', 'Двойные дефисы и пробелы запрещены'), django.core.validators.RegexValidator('^[а-яА-ЯёЁ]+(?:[- ]?[а-яА-ЯёЁ]+)*$', 'Разрешены только буквы русского алфавита, дефис, и символ пробела. Дефисы и пробелы не могут находиться в начале и в конце ввода')], verbose_name='Отчество')),
                ('role', models.CharField(choices=[('admin', 'Администратор'), ('moderator', 'Модератор'), ('psychologist', 'Психолог')], default='PSYCHOLOGIST', max_length=25)),
                ('photo', models.ImageField(blank=True, upload_to='photos/')),
                ('email', models.EmailField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9_.-]+[^-]@[a-z0-9.-]+\\.[a-z]{2,}$', 'Разрешены только строчные буквы латинского алфавита, цифры, и символы “@”, “-”, “_” и “.”'), django.core.validators.RegexValidator('^([^-])(?!.*\\.\\-)(?!.*\\-\\.)(?!.*\\_\\.)(?!.*\\.\\_)(?!.*\\.\\.)', 'Запрещено использование тире в начале и конце, двойных точек, специальных символов, а так же комбинаций точки с тире и символом нижнего подчеркивания')], verbose_name='email адрес')),
                ('birth_date', models.DateField(blank=True, null=True, validators=[users.validators.birthday_validator])),
                ('approved_by_moderator', models.BooleanField(default=False, verbose_name='Подтверждение модератора')),
                ('is_reg_confirm_sent', models.BooleanField(default=False, verbose_name='Письмо о рег-и направлено')),
                ('is_approve_sent', models.BooleanField(default=False, verbose_name='Письмо о проверке док-в направлено')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('confirmation_code', models.CharField(blank=True, max_length=5)),
                ('greeting', models.TextField(blank=True, verbose_name='Приветственное сообщение')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Психолог',
                'verbose_name_plural': 'Психологи',
            },
        ),
        migrations.CreateModel(
            name='CustomClientUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('password', models.CharField(blank=True, max_length=128, verbose_name='password')),
                ('first_name', models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator('^(?!.*\\s{2})(?!.*\\-{2})', 'Двойные дефисы и пробелы запрещены'), django.core.validators.RegexValidator('^[а-яА-ЯёЁ]+(?:[- ]?[а-яА-ЯёЁ]+)*$', 'Разрешены только буквы русского алфавита, дефис, и символ пробела. Дефисы и пробелы не могут находиться в начале и в конце ввода')], verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator('^(?!.*\\s{2})(?!.*\\-{2})', 'Двойные дефисы и пробелы запрещены'), django.core.validators.RegexValidator('^[а-яА-ЯёЁ]+(?:[- ]?[а-яА-ЯёЁ]+)*$', 'Разрешены только буквы русского алфавита, дефис, и символ пробела. Дефисы и пробелы не могут находиться в начале и в конце ввода')], verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator('^(?!.*\\s{2})(?!.*\\-{2})', 'Двойные дефисы и пробелы запрещены'), django.core.validators.RegexValidator('^[а-яА-ЯёЁ]+(?:[- ]?[а-яА-ЯёЁ]+)*$', 'Разрешены только буквы русского алфавита, дефис, и символ пробела. Дефисы и пробелы не могут находиться в начале и в конце ввода')], verbose_name='Отчество')),
                ('photo', models.ImageField(blank=True, upload_to='photos/')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9_.-]+[^-]@[a-z0-9.-]+\\.[a-z]{2,}$', 'Разрешены только строчные буквы латинского алфавита, цифры, и символы “@”, “-”, “_” и “.”'), django.core.validators.RegexValidator('^([^-])(?!.*\\.\\-)(?!.*\\-\\.)(?!.*\\_\\.)(?!.*\\.\\_)(?!.*\\.\\.)', 'Запрещено использование тире в начале и конце, двойных точек, специальных символов, а так же комбинаций точки с тире и символом нижнего подчеркивания')], verbose_name='email адрес')),
                ('birth_date', models.DateField(blank=True, null=True, validators=[users.validators.birthday_validator])),
                ('is_active', models.BooleanField(default=True)),
                ('is_reg_confirm_sent', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('complaint', models.TextField()),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Название документа')),
                ('scan', models.ImageField(upload_to='scans', verbose_name='Скан документа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document', to=settings.AUTH_USER_MODEL, verbose_name='Психолог')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
    ]
