# Generated by Django 3.2.16 on 2024-01-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customclientuser',
            name='complaint_text',
            field=models.TextField(blank=True),
        ),
    ]
