# Generated by Django 3.2.16 on 2024-01-29 09:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customclientuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9_.-]+@[a-z0-9.-]+\\.[a-zA-Z]{2,}$', 'Разрешены только строчные буквы латинского алфавита, цифры, и символы\n       “@”, “-”, “_” и “.”.'), django.core.validators.RegexValidator('^(?!.*\\.\\-)(?!.*\\-\\.)(?!.*\\_\\.)(?!.*\\.\\_)(?!.*\\.\\.)', 'Запрещено использование двойных точек, специальных символов,\n       а так же комбинаций точки с тире и символом нижнего подчеркивания')], verbose_name='email адрес'),
        ),
        migrations.AlterField(
            model_name='customclientuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator('^(?!.*\\s{2})(?!.*\\-{2})', 'Двойные дефисы и пробелы запрещены'), django.core.validators.RegexValidator('^[^- ][а-яА-ЯёЁ\\s-]+[^- ]$', 'Разрешены только буквы русского\n                                      алфавита, дефис, и символ пробела.\n                                      Дефисы и пробелы не могут находиться\n                                      в начале и в конце')], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='customclientuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator('^(?!.*\\s{2})(?!.*\\-{2})', 'Двойные дефисы и пробелы запрещены'), django.core.validators.RegexValidator('^[^- ][а-яА-ЯёЁ\\s-]+[^- ]$', 'Разрешены только буквы русского\n                                      алфавита, дефис, и символ пробела.\n                                      Дефисы и пробелы не могут находиться\n                                      в начале и в конце')], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='customclientuser',
            name='patronymic',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator('^(?!.*\\s{2})(?!.*\\-{2})', 'Двойные дефисы и пробелы запрещены'), django.core.validators.RegexValidator('^[^- ][а-яА-ЯёЁ\\s-]+[^- ]$', 'Разрешены только буквы русского\n                                      алфавита, дефис, и символ пробела.\n                                      Дефисы и пробелы не могут находиться\n                                      в начале и в конце')], verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9_.-]+@[a-z0-9.-]+\\.[a-zA-Z]{2,}$', 'Разрешены только строчные буквы латинского алфавита, цифры, и символы\n       “@”, “-”, “_” и “.”.'), django.core.validators.RegexValidator('^(?!.*\\.\\-)(?!.*\\-\\.)(?!.*\\_\\.)(?!.*\\.\\_)(?!.*\\.\\.)', 'Запрещено использование двойных точек, специальных символов,\n       а так же комбинаций точки с тире и символом нижнего подчеркивания')], verbose_name='email адрес'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^(?!.*\\s{2})(?!.*\\-{2})', 'Двойные дефисы и пробелы запрещены'), django.core.validators.RegexValidator('^[^- ][а-яА-ЯёЁ\\s-]+[^- ]$', 'Разрешены только буквы русского\n                                      алфавита, дефис, и символ пробела.\n                                      Дефисы и пробелы не могут находиться\n                                      в начале и в конце')], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^(?!.*\\s{2})(?!.*\\-{2})', 'Двойные дефисы и пробелы запрещены'), django.core.validators.RegexValidator('^[^- ][а-яА-ЯёЁ\\s-]+[^- ]$', 'Разрешены только буквы русского\n                                      алфавита, дефис, и символ пробела.\n                                      Дефисы и пробелы не могут находиться\n                                      в начале и в конце')], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='patronymic',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator('^(?!.*\\s{2})(?!.*\\-{2})', 'Двойные дефисы и пробелы запрещены'), django.core.validators.RegexValidator('^[^- ][а-яА-ЯёЁ\\s-]+[^- ]$', 'Разрешены только буквы русского\n                                      алфавита, дефис, и символ пробела.\n                                      Дефисы и пробелы не могут находиться\n                                      в начале и в конце')], verbose_name='Отчество'),
        ),
    ]
