# Generated by Django 3.2.16 on 2024-02-09 12:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customclientuser',
            name='password',
            field=models.CharField(blank=True, max_length=128, validators=[django.core.validators.RegexValidator('^[A-Za-z\\d@$!%*#?&-]{8,20}$', 'Пароль должен содержать не менее восьми и не более двадцати символов, разрешены буквы латинского алфавита, специальные символы без ограничений, а так же цифры. Регистр букв имеет значение'), django.core.validators.RegexValidator('^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*#?&-])', 'Пароль должен содержать как миним одну строчную букву, как минимум одну заглавную, как минимум одну цифру, и как минимуи один специальный символ')], verbose_name='password'),
        ),
    ]
