# Generated by Django 3.2.16 on 2024-02-02 12:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customclientuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9_.-]+[^-]@[a-z0-9.-]+\\.[a-z]{2,}$', 'Разрешены только строчные буквы латинского алфавита, цифры, и символы “@”, “-”, “_” и “.”'), django.core.validators.RegexValidator('^([^-])(?!.*\\.\\-)(?!.*\\-\\.)(?!.*\\_\\.)(?!.*\\.\\_)(?!.*\\.\\.)', 'Запрещено использование тире в начале и конце, двойных точек, специальных символов, а так же комбинаций точки с тире и символом нижнего подчеркивания')], verbose_name='email адрес'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9_.-]+[^-]@[a-z0-9.-]+\\.[a-z]{2,}$', 'Разрешены только строчные буквы латинского алфавита, цифры, и символы “@”, “-”, “_” и “.”'), django.core.validators.RegexValidator('^([^-])(?!.*\\.\\-)(?!.*\\-\\.)(?!.*\\_\\.)(?!.*\\.\\_)(?!.*\\.\\.)', 'Запрещено использование тире в начале и конце, двойных точек, специальных символов, а так же комбинаций точки с тире и символом нижнего подчеркивания')], verbose_name='email адрес'),
        ),
    ]
