# Generated by Django 3.2.16 on 2024-02-11 14:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20240202_1613'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ('pk',), 'verbose_name': 'Психолог', 'verbose_name_plural': 'Психологи'},
        ),
        migrations.AlterField(
            model_name='customclientuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator('^(?!.*\\s{2})(?!.*\\-{2})', 'Двойные дефисы и пробелы запрещены'), django.core.validators.RegexValidator('^[а-яА-ЯёЁ]+(?:[- ]?[а-яА-ЯёЁ]+)*$', 'Разрешены только буквы русского алфавита, дефис, и символ пробела. Дефисы и пробелы не могут находиться в начале и в конце ввода')], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='customclientuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator('^(?!.*\\s{2})(?!.*\\-{2})', 'Двойные дефисы и пробелы запрещены'), django.core.validators.RegexValidator('^[а-яА-ЯёЁ]+(?:[- ]?[а-яА-ЯёЁ]+)*$', 'Разрешены только буквы русского алфавита, дефис, и символ пробела. Дефисы и пробелы не могут находиться в начале и в конце ввода')], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='customclientuser',
            name='patronymic',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator('^(?!.*\\s{2})(?!.*\\-{2})', 'Двойные дефисы и пробелы запрещены'), django.core.validators.RegexValidator('^[а-яА-ЯёЁ]+(?:[- ]?[а-яА-ЯёЁ]+)*$', 'Разрешены только буквы русского алфавита, дефис, и символ пробела. Дефисы и пробелы не могут находиться в начале и в конце ввода')], verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^(?!.*\\s{2})(?!.*\\-{2})', 'Двойные дефисы и пробелы запрещены'), django.core.validators.RegexValidator('^[а-яА-ЯёЁ]+(?:[- ]?[а-яА-ЯёЁ]+)*$', 'Разрешены только буквы русского алфавита, дефис, и символ пробела. Дефисы и пробелы не могут находиться в начале и в конце ввода')], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^(?!.*\\s{2})(?!.*\\-{2})', 'Двойные дефисы и пробелы запрещены'), django.core.validators.RegexValidator('^[а-яА-ЯёЁ]+(?:[- ]?[а-яА-ЯёЁ]+)*$', 'Разрешены только буквы русского алфавита, дефис, и символ пробела. Дефисы и пробелы не могут находиться в начале и в конце ввода')], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='patronymic',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator('^(?!.*\\s{2})(?!.*\\-{2})', 'Двойные дефисы и пробелы запрещены'), django.core.validators.RegexValidator('^[а-яА-ЯёЁ]+(?:[- ]?[а-яА-ЯёЁ]+)*$', 'Разрешены только буквы русского алфавита, дефис, и символ пробела. Дефисы и пробелы не могут находиться в начале и в конце ввода')], verbose_name='Отчество'),
        ),
    ]
