# Generated by Django 3.2.16 on 2024-01-10 15:09

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='faculty',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название факультета'),
        ),
        migrations.AddField(
            model_name='education',
            name='scan',
            field=models.ImageField(default=1950, upload_to='scans/<django.db.models.fields.related.ForeignKey>/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='education',
            name='specialization',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название специальности'),
        ),
        migrations.AddField(
            model_name='education',
            name='university',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название учебного заведения'),
        ),
        migrations.AddField(
            model_name='education',
            name='year_of_graduation',
            field=models.IntegerField(default=1980, validators=[users.validators.year_validator], verbose_name='Год окончания'),
            preserve_default=False,
        ),
    ]
