# Generated by Django 3.2.16 on 2024-01-13 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_greeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='id',
            field=models.AutoField(default=1000000, primary_key=True, serialize=False),
        ),
    ]
