# Generated by Django 3.2.16 on 2024-02-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customclientuser',
            name='photo',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='document',
            name='scan',
            field=models.ImageField(upload_to='', verbose_name='Скан документа'),
        ),
    ]
