# Generated by Django 3.2.16 on 2024-02-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20240219_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='scan',
            field=models.ImageField(upload_to=''),
        ),
    ]
