# Generated by Django 3.2.16 on 2024-01-10 17:39

import birthday.fields
from django.db import migrations
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20240110_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='birthday_dayofyear_internal',
            new_name='birth_date_dayofyear_internal',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='birthday',
        ),
        migrations.AddField(
            model_name='customuser',
            name='birth_date',
            field=birthday.fields.BirthdayField(blank=True, null=True, validators=[users.validators.birthday_validator]),
        ),
    ]
