# Generated by Django 3.2.16 on 2024-01-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_education_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customclientuser',
            name='id',
            field=models.AutoField(default=1000000, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='education',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
