# Generated by Django 3.2.16 on 2024-01-10 17:39

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20240110_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='birth_date_dayofyear_internal',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(blank=True, null=True, validators=[users.validators.birthday_validator]),
        ),
    ]
