# Generated by Django 3.2.16 on 2024-01-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customclientuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='year_of_graduation',
            field=models.IntegerField(blank=True, verbose_name='Год окончания'),
        ),
    ]
