# Generated by Django 3.2.16 on 2024-01-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_education_year_of_graduation'),
    ]

    operations = [
        migrations.AddField(
            model_name='customclientuser',
            name='is_reg_confirm_sended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_approve_sended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_reg_confirm_sended',
            field=models.BooleanField(default=False),
        ),
    ]
