# Generated by Django 3.2.16 on 2024-01-14 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20240114_2259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customclientuser',
            old_name='is_reg_confirm_sended',
            new_name='is_reg_confirm_sent',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='is_approve_sended',
            new_name='is_approve_sent',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='is_reg_confirm_sended',
            new_name='is_reg_confirm_sent',
        ),
    ]
