# Generated by Django 3.2.16 on 2024-01-26 11:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20240114_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customclientuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator("^[a-z0-9_!#$%&'*+\\/=?`{|}~^.-]+@[a-z0-9.-]+$", 'Разрешены только буквы латинского\n                                       алфавита, цифры, и символы\n                                       “@”, “-”, “_” и “.”. ')], verbose_name='email адрес'),
        ),
    ]
