# Generated by Django 3.2.16 on 2024-01-26 14:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20240126_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customclientuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator("^[a-z0-9_!#$%&'*+\\/=?`{|}~^.-]+@[a-z0-9.-]+$", 'Разрешены только строчные буквы латинского\n    алфавита, цифры, и символы\n    “@”, “-”, “_” и “.”. ')], verbose_name='email адрес'),
        ),
        migrations.AlterField(
            model_name='customclientuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator('^([А-ЯЁ][а-яё]+[\\-\\s]?){3,}', 'Разрешены только буквы русского алфавита,\n                               дефис, и символ пробела')], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='customclientuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator('^([А-ЯЁ][а-яё]+[\\-\\s]?){3,}', 'Разрешены только буквы русского алфавита,\n                               дефис, и символ пробела')], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='customclientuser',
            name='patronymic',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator('^([А-ЯЁ][а-яё]+[\\-\\s]?){3,}', 'Разрешены только буквы русского алфавита,\n                               дефис, и символ пробела')], verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator("^[a-z0-9_!#$%&'*+\\/=?`{|}~^.-]+@[a-z0-9.-]+$", 'Разрешены только строчные буквы латинского\n    алфавита, цифры, и символы\n    “@”, “-”, “_” и “.”. ')], verbose_name='email адрес'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^([А-ЯЁ][а-яё]+[\\-\\s]?){3,}', 'Разрешены только буквы русского алфавита,\n                               дефис, и символ пробела')], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^([А-ЯЁ][а-яё]+[\\-\\s]?){3,}', 'Разрешены только буквы русского алфавита,\n                               дефис, и символ пробела')], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='patronymic',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator('^([А-ЯЁ][а-яё]+[\\-\\s]?){3,}', 'Разрешены только буквы русского алфавита,\n                               дефис, и символ пробела')], verbose_name='Отчество'),
        ),
    ]
