# Generated by Django 3.2.16 on 2024-01-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20240124_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название документа'),
        ),
    ]
