# Generated by Django 3.2.16 on 2024-01-28 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20240126_1545'),
        ('users', '0014_education_name'),
    ]

    operations = [
    ]
