# Generated by Django 3.2.16 on 2024-01-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_education_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='approved_by_moderator',
            field=models.BooleanField(default=True),
        ),
    ]
