# Generated by Django 3.2.16 on 2024-01-28 20:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_merge_0013_auto_20240126_1545_0014_education_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customclientuser',
            name='complaint',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='customclientuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator("^[a-z0-9_!#$%&'*+\\/=?`{|}~^.-]+@[a-z0-9.-]+$", 'Разрешены только строчные буквы латинского алфавита, цифры, и символы\n       “@”, “-”, “_” и “.”.'), django.core.validators.RegexValidator('^(?!.*\\.\\-)(?!.*\\-\\.)(?!.*\\_\\.)(?!.*\\.\\_)', 'Запрещено использование двойных точек,\n       а так же комбинаций точки с тире и символом нижнего подчеркивания')], verbose_name='email адрес'),
        ),
        migrations.AlterField(
            model_name='customclientuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator('^[-а-яА-ЯёЁ -]+(\\s+[-а-яА-ЯёЁ -]+)*$', 'Разрешены только буквы русского\n                                      алфавита, дефис, и символ пробела')], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='customclientuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator('^[-а-яА-ЯёЁ -]+(\\s+[-а-яА-ЯёЁ -]+)*$', 'Разрешены только буквы русского\n                                      алфавита, дефис, и символ пробела')], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='customclientuser',
            name='patronymic',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator('^[-а-яА-ЯёЁ -]+(\\s+[-а-яА-ЯёЁ -]+)*$', 'Разрешены только буквы русского\n                                      алфавита, дефис, и символ пробела')], verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator("^[a-z0-9_!#$%&'*+\\/=?`{|}~^.-]+@[a-z0-9.-]+$", 'Разрешены только строчные буквы латинского алфавита, цифры, и символы\n       “@”, “-”, “_” и “.”.'), django.core.validators.RegexValidator('^(?!.*\\.\\-)(?!.*\\-\\.)(?!.*\\_\\.)(?!.*\\.\\_)', 'Запрещено использование двойных точек,\n       а так же комбинаций точки с тире и символом нижнего подчеркивания')], verbose_name='email адрес'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[-а-яА-ЯёЁ -]+(\\s+[-а-яА-ЯёЁ -]+)*$', 'Разрешены только буквы русского\n                                      алфавита, дефис, и символ пробела')], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[-а-яА-ЯёЁ -]+(\\s+[-а-яА-ЯёЁ -]+)*$', 'Разрешены только буквы русского\n                                      алфавита, дефис, и символ пробела')], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='patronymic',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator('^[-а-яА-ЯёЁ -]+(\\s+[-а-яА-ЯёЁ -]+)*$', 'Разрешены только буквы русского\n                                      алфавита, дефис, и символ пробела')], verbose_name='Отчество'),
        ),
    ]
