# Generated by Django 3.2.16 on 2024-02-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_customuser_approved_by_moderator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='approved_by_moderator',
            field=models.BooleanField(default=False),
        ),
    ]
